 const eventsData = [
    {
      id: 1,
      title: 'React Workshop',
      description: 'A workshop on modern React techniques and hooks.',
      date: '2024-09-30',
      time: '10:00',
      location: 'Tech Hall, Building A',
      status: 'Upcoming',
    },
    {
      id: 2,
      title: 'Node.js Conference',
      description: 'Explore the latest in server-side development with Node.js.',
      date: '2024-08-20',
      time: '09:00',
      location: 'Auditorium, Building B',
      status: 'Past',
    },
    {
      id: 3,
      title: 'JavaScript Meetup',
      description: 'An event for JavaScript enthusiasts to share and learn.',
      date: '2024-10-10',
      time: '11:00',
      location: 'Community Hall, Building C',
      status: 'Upcoming',
    },
    {
      id: 4,
      title: 'UI/UX Design Summit',
      description: 'A full-day event focusing on modern UI/UX design principles.',
      date: '2024-09-15',
      time: '08:00',
      location: 'Design Lab, Building D',
      status: 'Upcoming',
    },
    {
      id: 5,
      title: 'Machine Learning Bootcamp',
      description: 'Hands-on sessions covering the latest trends in machine learning.',
      date: '2024-08-25',
      time: '10:00',
      location: 'Data Science Center, Building E',
      status: 'Past',
    },
    {
      id: 6,
      title: 'Cloud Computing Expo',
      description: 'Industry experts discuss advancements in cloud technologies.',
      date: '2024-11-05',
      time: '09:00',
      location: 'Expo Center, Building F',
      status: 'Upcoming',
    },
    {
      id: 7,
      title: 'DevOps Practices Workshop',
      description: 'Learn the best practices for DevOps and continuous integration.',
      date: '2024-09-25',
      time: '01:00',
      location: 'Innovation Hub, Building G',
      status: 'Upcoming',
    },
    {
      id: 8,
      title: 'Agile Methodologies Seminar',
      description: 'An in-depth look at Agile frameworks and team collaboration.',
      date: '2024-10-01',
      time: '11:00',
      location: 'Seminar Hall, Building H',
      status: 'Upcoming',
    },
    {
      id: 9,
      title: 'Cybersecurity Awareness Week',
      description: 'A week-long event raising awareness about cybersecurity threats and solutions.',
      date: '2024-07-15',
      time: '09:00',
      location: 'Security Conference Hall, Building I',
      status: 'Past',
    },
    {
      id: 10,
      title: 'Artificial Intelligence Symposium',
      description: 'A symposium on the latest developments in artificial intelligence.',
      date: '2024-11-20',
      time: '10:00',
      location: 'Tech Park, Building J',
      status: 'Upcoming',
    },
    {
      id: 11,
      title: 'Python Programming Crash Course',
      description: 'An intensive course on Python for beginners.',
      date: '2024-10-05',
      time: '02:00',
      location: 'Learning Center, Building K',
      status: 'Upcoming',
    },
    {
      id: 12,
      title: 'Blockchain Technology Forum',
      description: 'A forum for discussing the potential of blockchain across industries.',
      date: '2024-08-01',
      time: '09:30',
      location: 'Conference Room, Building L',
      status: 'Past',
    },
  ];
  export default eventsData;